package com.slaviboy.features.homeScreen.ui

import androidx.compose.ui.graphics.Color

val screenBackgroundColor = Color(0xFFEEEEEE)
val sectionBackgroundColor = Color(0xFFFFFFFF)
val bannerBackgroundColor = Color(0xFFFFFFFF)
val dividerColor = Color(0xFFFCFCFC)
val titleTextColor = Color(0xFF303030)
val subtitleTextColor = Color(0xFF929BA5)
val sectionTextColor = Color(0xFF929BA5)
val bannerTitleColor = Color(0xFF414448)
val bannerSubtitleColor = Color(0xFF95A0A9)
val bannerLinkTextColor = Color(0xFF3882BE)
val outputTextColor = Color(0xFF707070)
val outputResultBarColor = Color(0xFFA3AAC8)
val outputResultTextColor = Color(0xFF464646)
val iconNormalColor = Color(0xFFB4B4B4)
val iconSelectedColor = Color(0xFF3EA3E6)
val checkedColor = Color(0xFF27F26A)
val normalButtonColor = Color(0xFF0095F6)
val alertButtonColor = Color(0xFFD93838)
val buttonTextColor = Color(0xFFFFFFFF)
val canvasStrokeColor = Color(0xFF488EDE)
val dividerStrokeColor = Color(0xFFE5E4E4)
val itemBackgroundColor = Color(0xFFFFFFFF)
val itemTitleColor = Color(0xFF414448)
val itemSubtitleColor = Color(0xFF95A0A9)
val chevronColor = Color(0xFF919191)
val unfinishedTrainingState = Color(0xFFD8D8D8)
val finishedTrainingState = Color(0xFF488EDE)